# Generated by Django 4.1.3 on 2022-11-25 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.CharField(max_length=300, verbose_name='Описание')),
                ('full_description', models.CharField(max_length=1000, verbose_name='Полное описание')),
                ('price', models.CharField(max_length=255, verbose_name='Цена')),
                ('availability', models.CharField(max_length=255, verbose_name='Наличие')),
                ('sales', models.CharField(max_length=255, verbose_name='Кол-во продаж')),
                ('genre', models.CharField(max_length=255, verbose_name='Жанр')),
                ('platform', models.CharField(max_length=255, verbose_name='Платформа')),
                ('type', models.CharField(max_length=255, verbose_name='Тип')),
                ('img', models.ImageField(blank=True, db_index=True, null=True, upload_to='', verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Игра',
                'verbose_name_plural': 'игры',
            },
        ),
        migrations.CreateModel(
            name='Purchases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=255, verbose_name='Аккаунт')),
                ('number_purchase', models.CharField(max_length=255, verbose_name='Номер заказа')),
                ('platform', models.CharField(max_length=255, verbose_name='Платформа')),
                ('login', models.CharField(max_length=255, verbose_name='Логин')),
                ('password', models.CharField(max_length=255, verbose_name='Пароль')),
                ('time', models.DateTimeField(verbose_name='Время')),
            ],
            options={
                'verbose_name': 'Покупка',
                'verbose_name_plural': 'Покупки',
            },
        ),
    ]
