# Generated by Django 4.1.3 on 2022-12-06 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_account_full_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заглавие')),
                ('description', models.CharField(max_length=255, verbose_name='Описание')),
                ('photo', models.ImageField(blank=True, db_index=True, null=True, upload_to='', verbose_name='Картинка')),
            ],
        ),
    ]
