# Generated by Django 4.1.3 on 2022-12-18 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_info_options_polzovatel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polzovatel',
            name='mail',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Почта'),
        ),
    ]
