# Generated by Django 4.1.3 on 2022-12-24 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_polzovatel_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchases',
            name='polzovatel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.polzovatel', verbose_name='Пользователь'),
            preserve_default=False,
        ),
    ]
